### ISSUE TITLE
Not linking the (fail) outcomes gives an error

### ISSUE THREAD

**Issue by ipa-nhg-hd** [ipa320/airbus_coop#38]
I have checked out the latest `ssm_graphviz.py` from the ipa-led repo. But I still get the  error when one of the outcomes is not connected: 

```
[INFO] [WallTime: 1507288801.082653] [5171.791000] SSM is now ready !
Traceback (most recent call last):
  File "/home/administrator/airbus_ws/src/airbus_ssm_core/nodes/ssm_node.py", line 28, in <module>
    if(SSM._init_SSM()):
  File "/home/administrator/airbus_ws/src/airbus_ssm_core/src/airbus_ssm_core/ssm_main.py", line 65, in _init_SSM
    result = self.readSCXML()
  File "/home/administrator/airbus_ws/src/airbus_ssm_core/src/airbus_ssm_core/ssm_main.py", line 108, in readSCXML
    self._graphviz.start()
  File "/home/administrator/airbus_ws/src/airbus_ssm_core/src/airbus_ssm_core/ssm_graphviz.py", line 101, in start
    self.construct_subgraph(self._state_machine, 'ROOT', self._graph_dot)
  File "/home/administrator/airbus_ws/src/airbus_ssm_core/src/airbus_ssm_core/ssm_graphviz.py", line 140, in construct_subgraph
    self.create_edges(state, name, graph)
  File "/home/administrator/airbus_ws/src/airbus_ssm_core/src/airbus_ssm_core/ssm_graphviz.py", line 178, in create_edges
    if(('"parrallel_'+name+'_'+transition[2]+'"') in self._parallel_ending):
TypeError: cannot concatenate 'str' and 'NoneType' objects
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
[ssm_node-1] process has died [pid 26248, exit code -6, cmd /home/administrator/airbus_ws/src/airbus_ssm_core/nodes/ssm_node.py __name:=ssm_node __log:=/home/administrator/.ros/log/9b84c97a-aa7b-11e7-8989-9c5c8e021831/ssm_node-1.log].
log file: /home/administrator/.ros/log/9b84c97a-aa7b-11e7-8989-9c5c8e021831/ssm_node-1*.log
```

**Comment by ipa-led** [comment]
Ok, maybe still a case that i don't have checked yet. Can you send me the scxml file ? Thank you.

**Comment by ipa-nhg-hd** [comment]
________________________________

**Comment by ipa-led** [comment]
I have find the problem. Actually it should not be possible to not link outcomes for a parent state as it will raise a consistency error. The problem was  that the error was actually not raised but just printed out so the plugin would try to create a unconsistant dotgraph and crash. I will create a pull request for the fix.
